# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24a3f2df3ad45ff49bdf05c8ab67e648c3c5cd2906ecdd44d864693b4aaf7e4291506a5eed969873a0d9c0417e08b20af71376139dd90a4a25c20443820812db

test:
  secret_key_base: fd2405eba087a869b36f8b89d1c57f3d2eb5a18aa7d4a7af835ccbf85df4a2648916648829f0db48c7e821b04544cc0cf80e242465f77940b3533af8bb6438ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
